"""LLM client for generating daily reports using Gemini API - v2.0 Optimized Layout."""

from datetime import datetime
from typing import Optional
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from tenacity import (
    retry,
    stop_after_attempt,
    wait_exponential,
    retry_if_exception_type,
    before_sleep_log,
)

from .utils.logger import setup_logger

logger = setup_logger("generator")

load_dotenv()


class LLMClient:
    """Client for generating daily reports using Gemini API - v2.0 Chief Editor."""

    # v2.0 优化的系统提示 - 更好的排版和结构
    SYSTEM_PROMPT = """You are Cloud927, a Senior Solution Architect at Hikvision with a focus on Supply Chain AI.

## Your Mission
Transform raw data into actionable AI intelligence. You're not a news aggregator—you're an analyst who sees patterns and implications.

## v2.0 Output Format (Optimized Layout)

```markdown
# 🤖 {date} AI Daily Briefing

> **[核心发现一句话]** - One sentence that captures the most critical signal

---

### 📊 信号强度概览
| 领域 | 热度 | 重要发现 |
|------|------|----------|
| [AI模型] | 🔥🔥🔥 | xxx |
| [开源工具] | 🔥🔥 | xxx |
| [产品发布] | 🔥 | xxx |

---

## 🚨 Top Signal (必读)
> **重要性**: ⭐⭐⭐⭐⭐ | **来源**: {source}

**[标题](url)**
- 关键洞察: xxx
- 商业影响: xxx

### Cloud927 深度解读
> 从三个维度分析这个信号：

1. **供应链自动化** 💎
   - xxx

2. **个人AI Agent** 🤖
   - xxx

3. **Web3财富机会** 🪙
   - xxx

---

## 🛠️ 工程实践 (3-5条)
| 项目 | 解决的问题 | 技术亮点 |
|------|----------|---------|
| [name](url) | xxx | xxx |

---

## 🔬 研究前沿 (2-3条)
| 论文/模型 | 核心创新 | 应用场景 |
|----------|---------|---------|
| [name](url) | xxx | xxx |

---

## 🆕 产品雷达 (AI新品)
| 产品 | 定位 | 热度 |
|------|------|------|
| [name](url) | xxx | 👍👍 |

---

## 💬 社区声音 (1-2条)
> **[Reddit讨论](url)**
> 核心观点: xxx

---

## 🇨🇳 国内动态 (1-2条)
> **[V2EX讨论](url)**
> 关键观点: xxx

---

## 🎯 Cloud927 洞察
> **趋势判断**: [100+ words on the trajectory and implications]

> **行动建议**:
> - [立即可做]
> - [短期规划]
> - [长期观察]

---
*Generated by Cloud927 v2.0 | Data: HN, GH, HF, PH, Reddit, V2EX*
```

## Critical Rules
1. **Less is More** - Select only 5-8 most impactful items
2. **Structure First** - Use tables for scannability, prose for insights
3. **No Fabricated Links** - Only use provided URLs
4. **Chinese Output** - Simplified Chinese throughout
5. **80+ words minimum** for Closing Insight section

Remember: You're a senior architect. Analyze. Don't just summarize.
"""

    def __init__(self, api_key: Optional[str] = None):
        """Initialize the LLM client.

        Args:
            api_key: Gemini API key. If not provided, loads from environment.
        """
        self.api_key = api_key
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is required")

    @property
    def client(self):
        """Get or create the Gemini client using google-genai library."""
        if not hasattr(self, "_client"):
            self._client = genai.Client(api_key=self.api_key)
        return self._client

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=60),
        retry=retry_if_exception_type(Exception),
        before_sleep=before_sleep_log(logger, logger.level),
    )
    def generate_report(
        self,
        hn_data: list[dict],
        gh_data: list[dict],
        hf_data: list[dict],
        showhn_data: Optional[list[dict]] = None,
        v2ex_data: Optional[list[dict]] = None,
        ai_news_data: Optional[list[dict]] = None,
        ph_data: Optional[list[dict]] = None,
        reddit_data: Optional[list[dict]] = None,
        date: Optional[datetime] = None,
    ) -> str:
        """Generate a structured daily report from fetched data.

        Args:
            hn_data: List of Hacker News items.
            gh_data: List of GitHub trending items.
            hf_data: List of HuggingFace items.
            showhn_data: List of Show HN items.
            v2ex_data: List of V2EX discussions.
            ai_news_data: List of AI news from official blogs.
            ph_data: List of Product Hunt AI products.
            reddit_data: List of Reddit AI discussions.
            date: Date for the report. Defaults to today.

        Returns:
            Structured markdown report as a string.
        """
        if date is None:
            date = datetime.now()

        date_str = date.strftime("%Y-%m-%d")

        user_prompt = self._build_prompt(
            hn_data=hn_data,
            gh_data=gh_data,
            hf_data=hf_data,
            showhn_data=showhn_data or [],
            v2ex_data=v2ex_data or [],
            ai_news_data=ai_news_data or [],
            ph_data=ph_data or [],
            reddit_data=reddit_data or [],
            date_str=date_str,
        )

        logger.info(f"Generating v2.0 daily report for {date_str}")

        try:
            response = self.client.models.generate_content(
                model="gemini-2.0-flash",
                contents=[user_prompt],
                config={
                    "system_instruction": self.SYSTEM_PROMPT,
                }
            )
            report = response.text.strip()
            logger.info(f"Report generated: {len(report)} chars")
            return report

        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            raise

    def _format_item(self, item: dict, item_type: str) -> str:
        """Format a single data item."""
        title = item.get("title", item.get("name", "N/A"))
        url = item.get("url", "")
        lines = [f"**标题**: {title}", f"**链接**: {url}"]

        if item_type == "hn":
            score = item.get("score", 0)
            time_ago = item.get("time_ago", "")
            excerpt = item.get("excerpt", "")
            lines.extend([f"**分数**: {score}", f"**时间**: {time_ago}"])
            if excerpt:
                lines.append(f"**摘要**: {excerpt[:400]}")

        elif item_type == "gh":
            desc = item.get("description", "")
            lang = item.get("language", "")
            stars = item.get("stars", 0)
            readme = item.get("readme", "")
            lines.extend([f"**描述**: {desc}", f"**语言**: {lang}", f"**Stars**: {stars}"])
            if readme:
                lines.append(f"**README**: {readme[:400]}")

        elif item_type == "hf":
            abstract = item.get("abstract", "")
            lines.append(f"**摘要**: {abstract[:400]}")

        elif item_type == "showhn":
            readme = item.get("readme", "")
            votes = item.get("score", 0)
            lines.extend([f"**分数**: {votes}", f"**README**: {readme[:600]}"])

        elif item_type == "v2ex":
            content = item.get("content", "")
            replies = item.get("replies", 0)
            lines.extend([f"**内容**: {content[:400]}", f"**回复**: {replies}"])

        elif item_type == "ai_news":
            source = item.get("source", "")
            summary = item.get("summary", "")
            lines.extend([f"**来源**: {source}", f"**总结**: {summary[:400]}"])

        elif item_type == "ph":
            tagline = item.get("tagline", "")
            votes = item.get("votes", 0)
            lines.extend([f"**标语**: {tagline}", f"**热度**: {votes}"])

        elif item_type == "reddit":
            source = item.get("source", "")
            comments = item.get("comments", 0)
            lines.extend([f"**社区**: {source}", f"**评论**: {comments}"])

        return " | ".join(lines)

    def _build_prompt(
        self,
        hn_data: list[dict],
        gh_data: list[dict],
        hf_data: list[dict],
        showhn_data: list[dict],
        v2ex_data: list[dict],
        ai_news_data: list[dict],
        ph_data: list[dict],
        reddit_data: list[dict],
        date_str: str,
    ) -> str:
        """Build the user prompt with all v2.0 data sources."""

        total_items = len(hn_data) + len(gh_data) + len(hf_data) + len(showhn_data) + len(v2ex_data) + len(ai_news_data) + len(ph_data) + len(reddit_data)

        prompt = f"""# Raw Data for v2.0 Report - {date_str}
**Total Items**: {total_items}

---

## 🔥 Hacker News Top Stories ({len(hn_data)} items)
"""
        for i, item in enumerate(hn_data[:8], 1):
            prompt += f"### {i}. {self._format_item(item, 'hn')}\n---\n"

        prompt += f"\n## 🎯 Show HN Projects ({len(showhn_data)} items)\n"
        for i, item in enumerate(showhn_data[:3], 1):
            prompt += f"### {i}. {self._format_item(item, 'showhn')}\n---\n"

        prompt += f"\n## ⭐ GitHub Trending ({len(gh_data)} items)\n"
        for i, item in enumerate(gh_data[:8], 1):
            prompt += f"### {i}. {self._format_item(item, 'gh')}\n---\n"

        prompt += f"\n## 🧠 HuggingFace Papers & Models ({len(hf_data)} items)\n"
        for i, item in enumerate(hf_data[:5], 1):
            prompt += f"### {i}. {self._format_item(item, 'hf')}\n---\n"

        prompt += f"\n## 🤖 AI Official News ({len(ai_news_data)} items)\n"
        for i, item in enumerate(ai_news_data[:5], 1):
            prompt += f"### {i}. {self._format_item(item, 'ai_news')}\n---\n"

        prompt += f"\n## 🆕 Product Hunt AI ({len(ph_data)} items)\n"
        for i, item in enumerate(ph_data[:5], 1):
            prompt += f"### {i}. {self._format_item(item, 'ph')}\n---\n"

        prompt += f"\n## 💬 Reddit AI Discussions ({len(reddit_data)} items)\n"
        for i, item in enumerate(reddit_data[:5], 1):
            prompt += f"### {i}. {self._format_item(item, 'reddit')}\n---\n"

        prompt += f"\n## 🇨🇳 V2EX Discussions ({len(v2ex_data)} items)\n"
        for i, item in enumerate(v2ex_data[:3], 1):
            prompt += f"### {i}. {self._format_item(item, 'v2ex')}\n---\n"

        prompt += """
---

## 📝 Generation Instructions (IMPORTANT)

Using the v2.0 format, generate a comprehensive AI daily report:

1. **Signal Overview Table** - Categorize findings by domain and urgency
2. **Top Signal** - Select ONE most important item, provide deep 3-pillar analysis
3. **Engineering Practices** - GitHub projects, use table format
4. **Research Frontiers** - HF papers, use table format
5. **Product Radar** - PH launches, use table format
6. **Community Voice** - Top Reddit discussion
7. **China Dynamics** - V2EX insights
8. **Cloud927 Insight** - 100+ words on trajectory + action items

**Selection Criteria**:
- Prioritize AI/ML content over general tech
- Focus on actionable insights
- Balance across all 8 data sources
- Each item must add unique perspective

Write in Simplified Chinese. Use the v2.0 format exactly as specified.
"""

        return prompt
